### API OAuth2 UserInfo endpoint - openid scope only (returns sub claim)
GET {{host}}/userinfo
Accept: application/json
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

###
GET {{host}}/api
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Register member
POST {{host}}/api/members
Content-Type: application/json
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

{
  "firstName": "Alex",
  "lastName": "Novak",
  "dateOfBirth": "2012-05-14",
  "nationality": "CZ",
  "gender": "MALE",
  "email": "alex.novak@example.com",
  "phone": "+420777123456",
  "address": {
    "street": "Kvetna 12",
    "city": "Brno",
    "postalCode": "60200",
    "country": "CZ"
  },
  "guardian": {
    "relationship": "PARENT",
    "firstName": "Eva",
    "lastName": "Novakova",
    "email": "eva.novakova@example.com",
    "phone": "+420777654321"
  }
}

### Create event
POST {{host}}/api/events
Content-Type: application/json
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

{
  "name": "1. BZL: Kratky den",
  "eventDate": "2026-01-21",
  "location": "Dubnany",
  "organizer": "ZBM"
}

###

GET {{host}}/api/events
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

###

### Get all members compact (hal format)
GET {{host}}/api/members?view=compact
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### GET Jan Novak member
GET {{host}}/api/members/a7df1bbd-03b1-4f34-b88e-05ba899f1640
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### GET Eva Svobodova member
GET {{host}}/api/members/a8154bdb-89ca-4b9a-beb3-feec37f34a2f
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Update Admin only for Eva Svobodova
PATCH {{host}}/api/members/a8154bdb-89ca-4b9a-beb3-feec37f34a2f
Authorization: Bearer {{$auth.token("AuthorizationCode")}}
Content-Type: application/json

{
  "firstName": "Janicka"
}

### Update self-edit for Eva Svobodova
PATCH {{host}}/api/members/a8154bdb-89ca-4b9a-beb3-feec37f34a2f
Authorization: Bearer {{$auth.token("AuthorizationCode")}}
Content-Type: application/json

{
  "chipNumber": "12345"
}


### Suggest registration number
GET {{host}}/registrationNumber?sex=MALE&dateOfBirth=2020-10-11
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### GET Edit member form data
GET {{host}}/members/1/editMemberInfoForm
Content-Type: application/json
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### PUT Edit member form data
PUT {{host}}/members/1/editMemberInfoForm
Content-Type: application/json
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

{
  "identityCard": null,
  "nationality": "SK",
  "address": {
    "streetAndNumber": "Tesinska 12",
    "city": "Brno",
    "postalCode": "14245",
    "country": "CZ"
  },
  "contact": {
    "email": "test@test.cz",
    "phone": "9871234567789",
    "note": "Muj druhy email"
  },
  "guardians": [],
  "siCard": null,
  "bankAccount": null,
  "dietaryRestrictions": null,
  "drivingLicence": [],
  "medicCourse": true,
  "firstName": "John",
  "lastName": "Dow",
  "dateOfBirth": "2020-02-10",
  "birthCertificateNumber": null,
  "sex": "male"
}

### Get form data for Member Edit by Admin
GET {{host}}/members/1/editByAdminForm
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Update member info by ADMIN
PUT {{host}}/members/1/editByAdminForm
Content-Type: application/json
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

{
  "firstName": "Dave",
  "lastName": "Pol",
  "dateOfBirth": "1982-04-26",
  "birthCertificateNumber": "123456/780",
  "nationality": "CZ",
  "sex": "male"
}

###
GET {{host}}/members/1/editOwnMemberInfoForm
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

###
PUT {{host}}/members/1/editOwnMemberInfoForm
Authorization: Bearer {{$auth.token("AuthorizationCode")}}
Content-Type: application/json

{
  "identityCard": null,
  "nationality": "CZ",
  "address": {
    "streetAndNumber": "Nekde jinde 12",
    "city": "Brno",
    "postalCode": "63212",
    "country": "CZ"
  },
  "contact": {
    "email": "test@testx.com",
    "phone": "888888888",
    "note": null
  },
  "guardians": [],
  "siCard": 12345678,
  "bankAccount": "CZ1234567891000",
  "dietaryRestrictions": null,
  "drivingLicence": [],
  "medicCourse": false
}


### Membership suspension info
GET {{host}}/members/1/suspendMembershipForm
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Suspend membership
PUT {{host}}/members/1/suspendMembershipForm
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Get ORIS user info data
GET {{host}}/oris/userInfo/ZBM8003
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### GET ORIS user info data - unknown reg num
GET {{host}}/oris/userInfo/ZBM8002
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Get List of available grants
GET {{host}}/grants
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Get Member grants Form data
GET {{host}}/members/1/changeGrantsForm
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Update member grants
PUT {{host}}/members/1/changeGrantsForm
Authorization: Bearer {{$auth.token("AuthorizationCode")}}
Content-Type: application/json

{
  "grants": ["members:edit", "members:register"]
}

### Get events list
GET {{host}}/events
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Register member for event
POST {{host}}/events/1/registrations
Authorization: Bearer {{$auth.token("AuthorizationCode")}}
Content-Type: application/json

{
  "memberId": {
    "value": 2
  }
}

### Events where member is registered
GET {{host}}/member/2/registeredEvents
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

### Get event registrations
GET {{host}}/events/1/registrations
Authorization: Bearer {{$auth.token("AuthorizationCode")}}

###
DELETE {{host}}/events/1/registrations/2
Authorization: Bearer {{$auth.token("AuthorizationCode")}}
