### API OAuth2 test endpoint
GET {{host}}/oidc/userinfo
Accept: application/json
Authorization: Bearer {{$auth.token("frontend@Local")}}

### Register member
POST {{host}}/memberRegistrations
Authorization: Bearer {{$auth.token("frontend@Local")}}
Content-Type: application/json

{
  "registrationNumber": "ZBM2001",
  "firstName": "John",
  "lastName": "Dow",
  "dateOfBirth": "2020-02-10",
  "nationality": "SK",
  "sex": "male",
  "address": {
    "streetAndNumber": "Tesinska 12",
    "city": "Ostrava",
    "country": "CZ",
    "postalCode": "14245"
  },
  "contact": {
    "email": "test@test.cz",
    "phone": "1234567789",
    "note": "Muj email"
  }
}

### Get all members compact (hal format)
GET {{host}}/members?view=compact
Authorization: Bearer {{$auth.token("frontend")}}
Accept: application/hal+json

### Get all members compact (klabis format)
GET {{host}}/members?view=compact
Authorization: Bearer {{$auth.token("frontend")}}
Accept: application/klabis+json

### Get all members (full details)
GET {{host}}/members?view=full
Authorization: Bearer {{$auth.token("frontend")}}
Accept: application/klabis+json

### GET single member
GET {{host}}/members/1
Authorization: Bearer {{$auth.token("frontend")}}

### Suggest registration number
GET {{host}}/registrationNumber?sex=MALE&dateOfBirth=2020-10-11
Authorization: Bearer {{$auth.token("frontend")}}

### GET Edit member form data
GET {{host}}/members/1/editMemberInfoForm
Content-Type: application/json
Authorization: Bearer {{$auth.token("frontend")}}

### PUT Edit member form data
PUT {{host}}/members/1/editMemberInfoForm
Content-Type: application/json
Authorization: Bearer {{$auth.token("frontend")}}

{
  "identityCard": null,
  "nationality": "SK",
  "address": {
    "streetAndNumber": "Tesinska 12",
    "city": "Brno",
    "postalCode": "14245",
    "country": "CZ"
  },
  "contact": {
    "email": "test@test.cz",
    "phone": "9871234567789",
    "note": "Muj druhy email"
  },
  "guardians": [],
  "siCard": null,
  "bankAccount": null,
  "dietaryRestrictions": null,
  "drivingLicence": [],
  "medicCourse": true,
  "firstName": "John",
  "lastName": "Dow",
  "dateOfBirth": "2020-02-10",
  "birthCertificateNumber": null,
  "sex": "male"
}

### Get form data for Member Edit by Admin
GET {{host}}/members/1/editByAdminForm
Authorization: Bearer {{$auth.token("frontend")}}

### Update member info by ADMIN
PUT {{host}}/members/1/editByAdminForm
Content-Type: application/json
Authorization: Bearer {{$auth.token("frontend")}}

{
  "firstName": "Dave",
  "lastName": "Pol",
  "dateOfBirth": "1982-04-26",
  "birthCertificateNumber": "123456/780",
  "nationality": "CZ",
  "sex": "male"
}

###
GET {{host}}/members/1/editOwnMemberInfoForm
Authorization: Bearer {{$auth.token("frontend")}}

###
PUT {{host}}/members/1/editOwnMemberInfoForm
Authorization: Bearer {{$auth.token("frontend")}}
Content-Type: application/json

{
  "identityCard": null,
  "nationality": "CZ",
  "address": {
    "streetAndNumber": "Nekde jinde 12",
    "city": "Brno",
    "postalCode": "63212",
    "country": "CZ"
  },
  "contact": {
    "email": "test@testx.com",
    "phone": "888888888",
    "note": null
  },
  "guardians": [],
  "siCard": 12345678,
  "bankAccount": "CZ1234567891000",
  "dietaryRestrictions": null,
  "drivingLicence": [],
  "medicCourse": false
}


### Membership suspension info
GET {{host}}/members/1/suspendMembershipForm
Authorization: Bearer {{$auth.token("frontend")}}

### Suspend membership
PUT {{host}}/members/1/suspendMembershipForm
Authorization: Bearer {{$auth.token("frontend@Local")}}

### Get ORIS user info data
GET {{host}}/oris/userInfo/ZBM8003
Authorization: Bearer {{$auth.token("frontend")}}

### GET ORIS user info data - unknown reg num
GET {{host}}/oris/userInfo/ZBM8002
Authorization: Bearer {{$auth.token("frontend")}}

### Get List of available grants
GET {{host}}/grants
Authorization: Bearer {{$auth.token("frontend@Local")}}

### Get Member grants Form data
GET {{host}}/members/1/changeGrantsForm
Authorization: Bearer {{$auth.token("test")}}

### Update member grants
PUT {{host}}/members/1/changeGrantsForm
Authorization: Bearer {{$auth.token("test")}}
Content-Type: application/json

{
  "grants": ["members:edit", "members:register"]
}

### Get events list
GET {{host}}/events
Authorization: Bearer {{$auth.token("frontend@Local")}}

### Register member for event
POST {{host}}/events/91/registrations
Authorization: Bearer {{$auth.token("frontend@Local")}}
Content-Type: application/json

{
  "memberId": {
    "value": 2
  }
}

### Events where member is registered
GET {{host}}/member/2/registeredEvents
Authorization: Bearer {{$auth.token("frontend@Local")}}

###
DELETE {{host}}/events/91/registrations/2
Authorization: Bearer {{$auth.token("frontend@Local")}}