global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'klabis-backend'
    scheme: https
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8443' ]
    tls_config:
      insecure_skip_verify: true
