export {LogoutIcon} from './LogoutIcon.tsx'
export {DeleteIcon} from './DeleteIcon.tsx'
export {EditIcon} from './EditIcon.tsx'
export {NewspaperIcon} from './NewspaperIcon.tsx'
export {SyncIcon} from './SyncIcon.tsx'
export {SunIcon} from './SunIcon.tsx'
export {MoonIcon} from './MoonIcon.tsx'
export {ComputerDesktopIcon} from './ComputerDesktopIcon.tsx'
