/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package club.klabis.members.infrastructure.restapi;

import club.klabis.members.MemberId;
import club.klabis.members.application.EditMemberInfoUseCase;
import club.klabis.members.domain.forms.EditAnotherMemberInfoByAdminForm;
import club.klabis.members.infrastructure.restapi.dto.EditAnotherMemberDetailsFormApiDto;
import club.klabis.shared.ConversionService;
import club.klabis.shared.RFC7807ErrorResponseApiDto;
import club.klabis.shared.config.restapi.ApiController;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

@ApiController(path = "/members/{memberId}/editByAdminForm", openApiTagName = "Edit members")
public class AdminMemberEditUseCaseControllers {

    private final EditMemberInfoUseCase editMemberUseCase;
    private final ConversionService conversionService;

    public AdminMemberEditUseCaseControllers(EditMemberInfoUseCase editMemberUseCase, ConversionService conversionService) {
        this.editMemberUseCase = editMemberUseCase;
        this.conversionService = conversionService;
    }

    /**
     * GET /members/{memberId}/editByAdminForm : Returns data for edit member information form
     * Returns data for edit member information form  #### Required authorization requires &#x60;members:suspendMembership&#x60; grant
     *
     * @param memberId ID of member (required)
     * @return Club member updated successfully (status code 200)
     * or Invalid user input (status code 400)
     * or Missing required user authentication or authentication failed (status code 401)
     * or User is not allowed to perform requested operation (status code 403)
     * or Missing required user authentication or authentication failed (status code 404)
     */
    @Operation(
            operationId = "getMemberEditByAdminForm",
            summary = "Returns data for edit member information form",
            description = "Returns data for edit member information form  #### Required authorization requires `members:suspendMembership` grant",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Club member updated successfully", content = {
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid user input", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = RFC7807ErrorResponseApiDto.class))
                    }),
                    @ApiResponse(responseCode = "401", description = "Missing required user authentication or authentication failed", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = RFC7807ErrorResponseApiDto.class))
                    }),
                    @ApiResponse(responseCode = "403", description = "User is not allowed to perform requested operation", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = RFC7807ErrorResponseApiDto.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "Missing required user authentication or authentication failed", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = RFC7807ErrorResponseApiDto.class))
                    })
            }
    )
    @GetMapping
    public EditAnotherMemberDetailsFormApiDto getMemberEditByAdminForm(
            @Parameter(name = "memberId", description = "ID of member", required = true, in = ParameterIn.PATH) @PathVariable("memberId") MemberId memberId
    ) {
        EditAnotherMemberDetailsFormApiDto formData = conversionService.convert(editMemberUseCase.getEditAnotherMemberForm(
                memberId), EditAnotherMemberDetailsFormApiDto.class);

        return formData;
    }

    /**
     * PUT /members/{memberId}/editByAdminForm : Update member information
     *
     * @param memberId                           ID of member (required)
     * @param editAnotherMemberDetailsFormApiDto (required)
     * @return Club member updated successfully (status code 200)
     * or Invalid user input (status code 400)
     * or Missing required user authentication or authentication failed (status code 401)
     * or User is not allowed to perform requested operation (status code 403)
     * or Missing required user authentication or authentication failed (status code 404)
     */
    @Operation(
            operationId = "putMemberEditByAdminForm",
            summary = "Update member information",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Club member updated successfully"),
                    @ApiResponse(responseCode = "400", description = "Invalid user input", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = club.klabis.members.infrastructure.restapi.dto.MembersMemberIdEditMemberInfoFormGet400ResponseApiDto.class))
                    }),
                    @ApiResponse(responseCode = "401", description = "Missing required user authentication or authentication failed", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = RFC7807ErrorResponseApiDto.class))
                    }),
                    @ApiResponse(responseCode = "403", description = "User is not allowed to perform requested operation", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = club.klabis.members.infrastructure.restapi.dto.MembersMemberIdEditMemberInfoFormGet403ResponseApiDto.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "Missing required user authentication or authentication failed", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = RFC7807ErrorResponseApiDto.class))
                    })
            }
    )
    @PutMapping
    ResponseEntity<Void> putMemberEditByAdminForm(
            @Parameter(name = "memberId", description = "ID of member", required = true, in = ParameterIn.PATH) @PathVariable("memberId") MemberId memberId,
            @Parameter(name = "EditAnotherMemberDetailsFormApiDto", description = "", required = true) @Valid @RequestBody EditAnotherMemberDetailsFormApiDto editAnotherMemberDetailsFormApiDto
    ) {
        editMemberUseCase.editMember(memberId,
                conversionService.convert(editAnotherMemberDetailsFormApiDto, EditAnotherMemberInfoByAdminForm.class));
        return ResponseEntity.ok(null);
    }
}
