/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package club.klabis.members.infrastructure.restapi;

import club.klabis.finance.infrastructure.restapi.AccountReponse;
import club.klabis.members.MemberId;
import club.klabis.members.application.MembersRepository;
import club.klabis.members.domain.Member;
import club.klabis.members.domain.MemberNotFoundException;
import club.klabis.members.infrastructure.restapi.dto.MembersApiResponse;
import club.klabis.shared.config.hateoas.HalResourceAssembler;
import club.klabis.shared.config.hateoas.ModelAssembler;
import club.klabis.shared.config.hateoas.ModelPreparator;
import club.klabis.shared.config.hateoas.forms.KlabisHateoasImprovements;
import club.klabis.shared.config.restapi.ApiController;
import club.klabis.shared.config.restapi.JsonViewMapping;
import club.klabis.shared.config.restapi.JsonViewParameter;
import club.klabis.shared.config.restapi.ResponseViews;
import club.klabis.shared.config.security.ApplicationGrant;
import club.klabis.shared.config.security.KlabisSecurityService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import jakarta.validation.Valid;
import org.springdoc.core.converters.models.PageableAsQueryParam;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PagedResourcesAssembler;
import org.springframework.hateoas.EntityModel;
import org.springframework.hateoas.PagedModel;
import org.springframework.hateoas.server.ExposesResourceFor;
import org.springframework.hateoas.server.RepresentationModelProcessor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.server.ResponseStatusException;

import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;

@ExposesResourceFor(Member.class)
@ApiController(openApiTagName = "Members", path = "/members")
public class MembersApi {

    private final MembersRepository membersRepository;
    private final ModelAssembler<Member, MembersApiResponse> memberModelAssembler;
    private final KlabisSecurityService klabisSecurityService;

    public MembersApi(MembersRepository membersRepository, ModelPreparator<Member, MembersApiResponse> memberModelAssembler, PagedResourcesAssembler<Member> pagedAssembler, KlabisSecurityService klabisSecurityService) {
        this.membersRepository = membersRepository;
        this.klabisSecurityService = klabisSecurityService;
        this.memberModelAssembler = new HalResourceAssembler<>(memberModelAssembler, pagedAssembler);
    }

    /**
     * GET /members : List all club members
     * Returns a list of all club members
     *
     * @param suspended | value | effect | |---|---| | &#x60;true&#x60; | returns both active and suspended members |  | &#x60;false&#x60; | return only active members |  (optional, default to false)
     * @return A list of club members (status code 200)
     * or Missing required user authentication or authentication failed (status code 401)
     */
    @Operation(
            operationId = "membersGet",
            summary = "Club members list",
            description = "Returns club members",
            responses = {
                    @ApiResponse(responseCode = "200", description = "A list of club members"),
                    @ApiResponse(responseCode = "401", description = "Missing required user authentication or authentication failed", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = club.klabis.shared.RFC7807ErrorResponseApiDto.class))
                    })
            }
    )
    @GetMapping
    @PageableAsQueryParam
    @JsonViewParameter(name = "view", defaultValue = "SUMMARY", mapping = {
            @JsonViewMapping(name = "SUMMARY", jsonView = ResponseViews.Summary.class),
            @JsonViewMapping(name = "DETAILED", jsonView = ResponseViews.Detailed.class)
    })
    PagedModel<EntityModel<MembersApiResponse>> membersGet(
            @Valid @RequestParam(value = "suspended", required = false, defaultValue = "false") Boolean suspended,
            @Parameter(hidden = true) Pageable pageable
    ) {
        if (suspended && !klabisSecurityService.hasGrant(ApplicationGrant.MEMBERS_REGISTER)) {
            throw new ResponseStatusException(HttpStatus.FORBIDDEN,
                    "Displaying suspended members requires MEMBERS_REGISTER grant");
        }
        Page<Member> result = membersRepository.findAllBySuspended(suspended,
                memberModelAssembler.toDomainPageable(pageable));
        var resultModel = memberModelAssembler.toPagedResponse(result);
        if (klabisSecurityService.hasGrant(ApplicationGrant.MEMBERS_REGISTER)) {
            resultModel.add(linkTo(methodOn(getClass()).membersGet(!suspended,
                    pageable.first())).withRel(suspended ? "activeMembers" : "suspendedMembers"));
        }
        return resultModel;
    }

    /**
     * GET /members/{memberId} : Get member by ID
     * Returns a member
     *
     * @param memberId ID of member (required)
     * @return A single member (status code 200)
     * or Missing required user authentication or authentication failed (status code 401)
     * or Requested resource wasn&#39;t found (status code 404)
     */
    @Operation(
            operationId = "membersMemberIdGet",
            summary = "Get member by ID",
            description = "Returns a member",
            responses = {
                    @ApiResponse(responseCode = "200", description = "A single member"),
                    @ApiResponse(responseCode = "401", description = "Missing required user authentication or authentication failed", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = club.klabis.shared.RFC7807ErrorResponseApiDto.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "Requested resource wasn't found", content = {
                            @Content(mediaType = "application/problem+json", schema = @Schema(implementation = club.klabis.shared.RFC7807ErrorResponseApiDto.class))
                    })
            }
    )
    @GetMapping("/{memberId}")
    public EntityModel<MembersApiResponse> membersMemberIdGet(
            @Parameter(name = "memberId", description = "ID of member", required = true, in = ParameterIn.PATH) @PathVariable("memberId") MemberId memberId
    ) {
        return membersRepository.findById(memberId)
                .map(memberModelAssembler::toEntityResponse)
                .orElseThrow(() -> new MemberNotFoundException(memberId));
    }

}

@Component
class FinanceAccountRepresentationPostprocessor implements RepresentationModelProcessor<EntityModel<AccountReponse>> {

    @Override
    public EntityModel<AccountReponse> process(EntityModel<AccountReponse> model) {

        MemberId ownerId = model.getContent().ownerId();

        KlabisHateoasImprovements.linkIfAuthorized(methodOn(MembersApi.class).membersMemberIdGet(ownerId))
                .map(link -> link.withRel("owner"))
                .ifPresent(model::add);

        return model;

    }
}