/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserPermissions"];
        put: operations["updatePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List members with pagination and sorting
         * @description Retrieves a paginated list of registered members with summary information (firstName, lastName, registrationNumber). Supports pagination (page, size) and sorting (sort=field,direction). Default: page=0, size=10, sort=lastName,asc. Allowed sort fields: firstName, lastName, registrationNumber. Returns HATEOAS links for navigation including pagination links (first, last, next, prev).
         */
        get: operations["listMembers"];
        put?: never;
        /**
         * Register a new member
         * @description Creates a new member with personal information, contact details, and optional guardian information for minors. Automatically generates a unique registration number in format XXXYYSS (club code, birth year, sequence). Returns HATEOAS links for resource navigation.
         */
        post: operations["registerMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List events with pagination and filtering
         * @description Retrieves a paginated list of events. Supports filtering by status and sorting by various fields. Default: page=0, size=10, sort=eventDate,desc. Allowed sort fields: id, name, eventDate, location, organizer, status.
         */
        get: operations["listEvents"];
        put?: never;
        /**
         * Create a new event
         * @description Creates a new event in DRAFT status. Event coordinator ID is optional. Returns HATEOAS links for resource navigation.
         */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish an event
         * @description Transitions event from DRAFT to ACTIVE status.
         */
        post: operations["publishEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish an event
         * @description Transitions event from ACTIVE to FINISHED status.
         */
        post: operations["finishEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an event
         * @description Transitions event to CANCELLED status.
         */
        post: operations["cancelEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List event registrations
         * @description List all registrations for an event. SI card numbers are not included for privacy protection.
         */
        get: operations["listRegistrations"];
        put?: never;
        /**
         * Register for an event
         * @description Register the authenticated member for an event with SI card number. Only allowed for ACTIVE events. Returns HATEOAS links for resource navigation.
         */
        post: operations["registerForEvent"];
        /**
         * Unregister from an event
         * @description Unregister the authenticated member from an event. Only allowed before the event date.
         */
        delete: operations["unregisterFromEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-setup/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request new password setup token
         * @description Requests a new token if the previous one expired
         */
        post: operations["requestNewToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete password setup
         * @description Sets the user's password and activates the account
         */
        post: operations["completePasswordSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get member by ID
         * @description Retrieves detailed member information by ID including personal information, contact details, and guardian information if applicable. Returns HATEOAS links for navigation.
         */
        get: operations["getMember"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update member information (partial update)
         * @description Updates member information with PATCH semantics (partial update). Supports dual authorization: members can edit their own information (limited fields), users with MEMBERS:UPDATE authority can edit any member (all fields). Only provided fields are updated; null/missing fields keep existing values. Member-editable fields: email, phone, address, dietaryRestrictions. Admin-only fields: firstName, lastName, dateOfBirth, gender, chipNumber, identityCard, medicalCourse, trainerLicense, drivingLicenseGroup. Returns HATEOAS links for resource navigation.
         */
        patch: operations["updateMember"];
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get event by ID
         * @description Retrieves detailed event information by ID. Returns HATEOAS links based on event status.
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an event
         * @description Updates event information. Only allowed for DRAFT and ACTIVE events. Returns HATEOAS links for resource navigation.
         */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rootNavigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/registrations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get own registration
         * @description Get the authenticated member's registration details including SI card number.
         */
        get: operations["getOwnRegistration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-setup/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate password setup token
         * @description Validates a token before showing the password setup form
         */
        get: operations["validateToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdatePermissionsRequest: {
            authorities: ("MEMBERS:CREATE" | "MEMBERS:READ" | "MEMBERS:UPDATE" | "MEMBERS:DELETE" | "MEMBERS:PERMISSIONS" | "EVENTS:MANAGE")[];
        };
        PermissionsResponseModel: {
            /** Format: uuid */
            userId?: string;
            authorities?: string[];
            _links?: components["schemas"]["Links"];
        };
        AddressRequest: {
            street: string;
            city: string;
            postalCode: string;
            country: string;
        };
        /** @description Guardian information for minors */
        GuardianDTO: {
            /**
             * @description Guardian's first name
             * @example Pavel
             */
            firstName: string;
            /**
             * @description Guardian's last name
             * @example Novák
             */
            lastName: string;
            /**
             * @description Relationship to member (e.g., PARENT, LEGAL_GUARDIAN)
             * @example PARENT
             */
            relationship: string;
            /**
             * Format: email
             * @description Guardian's email address
             * @example pavel.novak@example.com
             */
            email: string;
            /**
             * @description Guardian's phone number
             * @example +420987654321
             */
            phone: string;
        };
        /** @description Member registration data including personal information, contacts, and optional guardian */
        RegisterMemberRequest: {
            /**
             * @description Member's first name
             * @example Jan
             */
            firstName: string;
            /**
             * @description Member's last name
             * @example Novák
             */
            lastName: string;
            /**
             * Format: date
             * @description Member's date of birth
             * @example 2005-05-15
             */
            dateOfBirth: string;
            /**
             * @description Nationality (ISO 3166-1 alpha-2 or alpha-3 code)
             * @example CZ
             */
            nationality: string;
            /**
             * @description Member's gender
             * @example MALE
             * @enum {string}
             */
            gender: "MALE" | "FEMALE";
            /**
             * Format: email
             * @description Email address
             * @example jan.novak@example.com
             */
            email: string;
            /**
             * @description Phone number
             * @example +420777123456
             */
            phone: string;
            /** @description Postal address */
            address: components["schemas"]["AddressRequest"];
            /** @description Guardian information (required for minors under 18) */
            guardian?: components["schemas"]["GuardianDTO"];
        };
        /** @description Member registration response with HATEOAS links */
        MemberRegistrationResponse: {
            /**
             * Format: uuid
             * @description Unique member identifier (UUID)
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * @description Member's first name
             * @example Jan
             */
            firstName?: string;
            /**
             * @description Member's last name
             * @example Novák
             */
            lastName?: string;
        };
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: unknown;
            };
        };
        /** @description Event creation data */
        CreateEventCommand: {
            name: string;
            /** Format: date */
            eventDate: string;
            location: string;
            organizer: string;
            websiteUrl?: string;
            /** Format: uuid */
            eventCoordinatorId?: string;
        };
        EventDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: date */
            eventDate?: string;
            location?: string;
            organizer?: string;
            websiteUrl?: string;
            /** Format: uuid */
            eventCoordinatorId?: string;
            /** @enum {string} */
            status?: "DRAFT" | "ACTIVE" | "FINISHED" | "CANCELLED";
        };
        EntityModelEventDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: date */
            eventDate?: string;
            location?: string;
            organizer?: string;
            websiteUrl?: string;
            /** Format: uuid */
            eventCoordinatorId?: string;
            /** @enum {string} */
            status?: "DRAFT" | "ACTIVE" | "FINISHED" | "CANCELLED";
            _links?: components["schemas"]["Links"];
        };
        /** @description Registration data */
        RegisterForEventCommand: {
            siCardNumber: string;
        };
        OwnRegistrationDto: {
            firstName?: string;
            lastName?: string;
            siCardNumber?: string;
            /** Format: date-time */
            registeredAt?: string;
        };
        /** @description Request for a new password setup token */
        TokenRequestRequest: {
            /**
             * @description The user's registration number (format: XXXYYDD)
             * @example 12345678
             */
            registrationNumber: string;
            /**
             * @description The member's email address
             * @example member@example.com
             */
            email: string;
        };
        /** @description Response for password setup token request */
        TokenRequestResponse: {
            /**
             * @description Success message
             * @example If your account is pending activation, you will receive an email with a new setup link.
             */
            message?: string;
        };
        /** @description Error response for password setup API errors */
        ErrorResponse: {
            /**
             * @description Error message describing what went wrong
             * @example Invalid token
             */
            message?: string;
        };
        /** @description Password setup request containing token and new credentials */
        SetPasswordRequest: {
            /**
             * @description The plain text token from email
             * @example abc123def456
             */
            token: string;
            /**
             * @description The new password (minimum 12 characters with uppercase, lowercase, number, and special character)
             * @example Password123!
             */
            password: string;
            /**
             * @description Password confirmation must match the password field
             * @example Password123!
             */
            passwordConfirmation: string;
        };
        /** @description Response for completed password setup */
        PasswordSetupResponse: {
            /**
             * @description Success message
             * @example Password set successfully
             */
            message?: string;
            /**
             * @description The user's registration number
             * @example 12345678
             */
            registrationNumber?: string;
        };
        IdentityCardDto: {
            cardNumber?: string;
            /** Format: date */
            validityDate?: string;
        };
        MedicalCourseDto: {
            /** Format: date */
            completionDate?: string;
            /** Format: date */
            validityDate?: string;
        };
        TrainerLicenseDto: {
            licenseNumber?: string;
            /** Format: date */
            validityDate?: string;
        };
        /** @description Partial update request - only include fields to update */
        UpdateMemberRequest: {
            email?: string;
            phone?: string;
            address?: components["schemas"]["AddressRequest"];
            firstName?: string;
            lastName?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            chipNumber?: string;
            identityCard?: components["schemas"]["IdentityCardDto"];
            medicalCourse?: components["schemas"]["MedicalCourseDto"];
            trainerLicense?: components["schemas"]["TrainerLicenseDto"];
            /** @enum {string} */
            drivingLicenseGroup?: "B" | "BE" | "C" | "C1" | "D" | "D1" | "T" | "AM" | "A1" | "A2" | "A";
            dietaryRestrictions?: string;
        };
        AddressResponse: {
            street?: string;
            city?: string;
            postalCode?: string;
            country?: string;
        };
        MemberDetailsResponse: {
            /** Format: uuid */
            id?: string;
            registrationNumber?: string;
            firstName?: string;
            lastName?: string;
            /** Format: date */
            dateOfBirth?: string;
            nationality?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            email?: string;
            phone?: string;
            address?: components["schemas"]["AddressResponse"];
            guardian?: components["schemas"]["GuardianDTO"];
            active?: boolean;
            chipNumber?: string;
            identityCard?: components["schemas"]["IdentityCardDto"];
            medicalCourse?: components["schemas"]["MedicalCourseDto"];
            trainerLicense?: components["schemas"]["TrainerLicenseDto"];
            /** @enum {string} */
            drivingLicenseGroup?: "B" | "BE" | "C" | "C1" | "D" | "D1" | "T" | "AM" | "A1" | "A2" | "A";
            dietaryRestrictions?: string;
        };
        /** @description Event update data */
        UpdateEventCommand: {
            name: string;
            /** Format: date */
            eventDate: string;
            location: string;
            organizer: string;
            websiteUrl?: string;
            /** Format: uuid */
            eventCoordinatorId?: string;
        };
        EntityModelRootModel: {
            _links?: components["schemas"]["Links"];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        /** @description Member summary with essential information and HATEOAS links */
        MemberSummaryResponse: {
            /**
             * Format: uuid
             * @description Unique member identifier (UUID)
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * @description Member's first name
             * @example Jan
             */
            firstName?: string;
            /**
             * @description Member's last name
             * @example Novák
             */
            lastName?: string;
            /**
             * @description Member's unique registration number
             * @example ZBM0501
             */
            registrationNumber?: string;
        };
        EventSummaryDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: date */
            eventDate?: string;
            location?: string;
            organizer?: string;
            /** @enum {string} */
            status?: "DRAFT" | "ACTIVE" | "FINISHED" | "CANCELLED";
        };
        RegistrationDto: {
            firstName?: string;
            lastName?: string;
            /** Format: date-time */
            registeredAt?: string;
        };
        CollectionModelRegistrationDto: {
            _embedded?: {
                registrationDtoList?: components["schemas"]["RegistrationDto"][];
            };
            _links?: components["schemas"]["Links"];
        };
        EntityModelOwnRegistrationDto: {
            firstName?: string;
            lastName?: string;
            siCardNumber?: string;
            /** Format: date-time */
            registeredAt?: string;
            _links?: components["schemas"]["Links"];
        };
        /** @description Response for token validation */
        ValidateTokenResponse: {
            /**
             * @description Whether the token is valid
             * @example true
             */
            valid?: boolean;
            /**
             * Format: date-time
             * @description When the token expires (ISO-8601 format)
             * @example 2024-12-31T23:59:59Z
             */
            expiresAt?: string;
        };
        Link: {
            href?: string;
            hreflang?: string;
            title?: string;
            type?: string;
            deprecation?: string;
            profile?: string;
            name?: string;
            templated?: boolean;
        };
        Links: {
            [key: string]: components["schemas"]["Link"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUserPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PermissionsResponseModel"];
                };
            };
        };
    };
    updatePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePermissionsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PermissionsResponseModel"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query: {
                /** @description Pagination parameters: page (default=0), size (default=10, max=100), sort (default=lastName,asc). Example: ?page=0&size=20&sort=lastName,asc&sort=firstName,asc */
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of members retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["MemberSummaryResponse"];
                };
            };
            /** @description Invalid request - invalid sort field or page parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized - authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden - insufficient permissions (requires MEMBERS:READ) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    registerMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMemberRequest"];
            };
        };
        responses: {
            /** @description Member successfully registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["MemberRegistrationResponse"];
                };
            };
            /** @description Validation error - invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized - authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden - insufficient permissions (requires MEMBERS:CREATE) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query: {
                /** @description Filter by event status (optional) */
                status?: "DRAFT" | "ACTIVE" | "FINISHED" | "CANCELLED";
                /** @description Pagination parameters: page, size, sort */
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of events retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EventSummaryDto"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventCommand"];
            };
        };
        responses: {
            /** @description Event successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EventDto"];
                };
            };
            /** @description Validation error - invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden - insufficient permissions (requires EVENTS:MANAGE) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    publishEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event published successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
            /** @description Invalid state transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
        };
    };
    finishEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event finished successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
            /** @description Invalid state transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
        };
    };
    cancelEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event cancelled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
            /** @description Invalid state transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelEventDto"];
                };
            };
        };
    };
    listRegistrations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of registrations retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["RegistrationDto"];
                };
            };
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["CollectionModelRegistrationDto"];
                };
            };
        };
    };
    registerForEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterForEventCommand"];
            };
        };
        responses: {
            /** @description Successfully registered for event */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["OwnRegistrationDto"];
                };
            };
            /** @description Unauthorized - authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden - user must have a member profile to register for events */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Registration Conflict - already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    unregisterFromEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully unregistered */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot unregister on or after event date */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized - authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Event or registration not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestNewToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequestRequest"];
            };
        };
        responses: {
            /** @description Request processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenRequestResponse"];
                };
            };
            /** @description Invalid registration number format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    completePasswordSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password set successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PasswordSetupResponse"];
                };
            };
            /** @description Invalid request (validation failed, bad token, password mismatch) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Token expired or already used */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Member UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["MemberDetailsResponse"];
                };
            };
            /** @description Unauthorized - authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden - insufficient permissions (requires MEMBERS:READ) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Member UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRequest"];
            };
        };
        responses: {
            /** @description Member updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["MemberDetailsResponse"];
                };
            };
            /** @description Validation error - invalid request data or empty update */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized - authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden - insufficient permissions (editing other member without admin permission, or accessing admin-only fields) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict - concurrent update (optimistic locking failure) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EventDto"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventCommand"];
            };
        };
        responses: {
            /** @description Event successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EventDto"];
                };
            };
            /** @description Validation error or invalid state transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    rootNavigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/hal+json": components["schemas"]["EntityModelRootModel"];
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelRootModel"];
                };
            };
        };
    };
    getOwnRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own registration retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["OwnRegistrationDto"];
                };
            };
            /** @description Unauthorized - authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelOwnRegistrationDto"];
                };
            };
            /** @description Event or registration not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/prs.hal-forms+json": components["schemas"]["EntityModelOwnRegistrationDto"];
                };
            };
        };
    };
    validateToken: {
        parameters: {
            query: {
                /**
                 * @description The plain text token from the email link
                 * @example abc123def456
                 */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token is valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ValidateTokenResponse"];
                };
            };
            /** @description Invalid token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ValidateTokenResponse"];
                };
            };
            /** @description Token expired or already used */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ValidateTokenResponse"];
                };
            };
        };
    };
}
