export {LogoutIcon} from './LogoutIcon'
export {DeleteIcon} from './DeleteIcon'
export {EditIcon} from './EditIcon'
export {NewspaperIcon} from './NewspaperIcon'
export {SyncIcon} from './SyncIcon'
export {SunIcon} from './SunIcon'
export {MoonIcon} from './MoonIcon'
export {ComputerDesktopIcon} from './ComputerDesktopIcon'
