/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package club.klabis.users.adapters.restapi;

import club.klabis.users.adapters.restapi.dto.GetAllGrants200ResponseApiDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-07-25T23:04:18.674684470+02:00[Europe/Prague]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "security", description = "API used to control authentication and authorization")
public interface GrantsApi {

    /**
     * GET /grants : returns details about available security grants what can be assigned to users
     *
     * @return List of grants which can be assigned to members (status code 200)
     */
    @Operation(
            operationId = "getAllGrants",
            summary = "returns details about available security grants what can be assigned to users",
            tags = {"security"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "List of grants which can be assigned to members", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = GetAllGrants200ResponseApiDto.class))
                    })
            },
            security = {
                    @SecurityRequirement(name = "klabis", scopes = {"openid"})
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/grants",
            produces = {"application/json"}
    )
    ResponseEntity<GetAllGrants200ResponseApiDto> getAllGrants(

    );

}
