/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package club.klabis.events.infrastructure.restapi;

import club.klabis.events.application.EventManagementForm;
import club.klabis.events.application.EventsRepository;
import club.klabis.events.domain.Competition;
import club.klabis.events.domain.Event;
import club.klabis.events.domain.EventException;
import club.klabis.events.infrastructure.restapi.dto.EventResponse;
import club.klabis.shared.config.hateoas.HalResourceAssembler;
import club.klabis.shared.config.hateoas.ModelAssembler;
import club.klabis.shared.config.hateoas.RootModel;
import club.klabis.shared.config.restapi.ApiController;
import club.klabis.shared.config.restapi.ResponseViews;
import club.klabis.shared.config.security.ApplicationGrant;
import club.klabis.shared.config.security.HasGrant;
import com.fasterxml.jackson.annotation.JsonView;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import org.springdoc.core.converters.models.PageableAsQueryParam;
import org.springframework.core.annotation.Order;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PagedResourcesAssembler;
import org.springframework.hateoas.EntityModel;
import org.springframework.hateoas.LinkRelation;
import org.springframework.hateoas.PagedModel;
import org.springframework.hateoas.server.ExposesResourceFor;
import org.springframework.hateoas.server.LinkRelationProvider;
import org.springframework.hateoas.server.RepresentationModelProcessor;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;

@ExposesResourceFor(Event.class)
@ApiController(openApiTagName = "Events", path = "/events")
public class EventsController {
    private final EventsRepository eventsRepository;
    private final ModelAssembler<Event, EventResponse> eventModelMapper;

    EventsController(EventsRepository eventsRepository, EventModelMapper eventModelMapper, PagedResourcesAssembler<Event> pagedResourceAssembler) {
        this.eventsRepository = eventsRepository;
        this.eventModelMapper = new HalResourceAssembler<>(eventModelMapper, pagedResourceAssembler);
    }

    /**
     * GET /events : Returns events
     *
     * @return Events (status code 200)
     */
    @Operation(
            operationId = "getEvents",
            summary = "Returns events",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Events")
            }
    )
    @GetMapping
    @PageableAsQueryParam
    @JsonView(ResponseViews.Summary.class)
    PagedModel<EntityModel<EventResponse>> getEvents(@ModelAttribute EventsRepository.EventsQuery filter, @Parameter(hidden = true) Pageable pageable) {
        Page<Event> data = eventsRepository.findEvents(filter, pageable);

        return eventModelMapper.toPagedResponse(data);
    }

    @Operation(
            operationId = "createEvent",
            summary = "Creates new event"
    )
    @PostMapping
    @HasGrant(ApplicationGrant.EVENTS_MANAGE)
    public ResponseEntity<?> createEvent(@RequestBody EventManagementForm form) {
        Event createdEvent = eventsRepository.save(form.createNew());

        return ResponseEntity.created(linkTo(methodOn(getClass()).getEventById(createdEvent.getId())).toUri()).build();
    }

    @Operation(
            operationId = "getEventById",
            summary = "Returns event details",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Event details")
            },
            parameters = {
                    @Parameter(name = "eventId", description = "ID eventu", required = true, in = ParameterIn.PATH, schema = @Schema(type = "integer"))
            }
    )
    @GetMapping(value = "/{eventId}")
    @JsonView(ResponseViews.Detailed.class)
    EntityModel<EventResponse> getEventById(@PathVariable("eventId") Event.Id eventId) {
        return eventsRepository.findById(eventId)
                .map(eventModelMapper::toEntityResponse)
                .orElseThrow(() -> EventException.createEventNotFoundException(eventId));
    }

    @Operation(
            operationId = "updateEventById",
            summary = "Updates given event"
    )
    @PutMapping(value = "/{eventId}")
    @HasGrant(ApplicationGrant.EVENTS_MANAGE)
    public ResponseEntity<?> updateEventById(@PathVariable("eventId") Event.Id eventId, @RequestBody EventManagementForm form) {
        return eventsRepository.findById(eventId)
                .map(form::apply)
                .map(eventsRepository::save)
                .map(e -> ResponseEntity.ok().build())
                .orElseThrow(() -> EventException.createEventNotFoundException(eventId));
    }


    @GetMapping("/{eventId}/categories")
    public List<String> getEventCategories(@PathVariable Event.Id eventId) {
        Event event = eventsRepository.findById(eventId)
                .orElseThrow(() -> EventException.createEventNotFoundException(eventId));

        if (event instanceof Competition competition) {
            return competition.getCategories().stream().map(Competition.Category::name).toList();
        }
        return List.of();
    }

}

@Component
@Order(2)
class EventsRootPostprocessor implements RepresentationModelProcessor<EntityModel<RootModel>> {
    private final LinkRelationProvider linkRelationProvider;

    public EventsRootPostprocessor(LinkRelationProvider linkRelationProvider) {
        this.linkRelationProvider = linkRelationProvider;
    }

    @Override
    public EntityModel<RootModel> process(EntityModel<RootModel> model) {
        LinkRelation eventsRelation = linkRelationProvider.getCollectionResourceRelFor(Event.class);

        model.add(linkTo(methodOn(EventsController.class).getEvents(null, null)).withRel(eventsRelation));


        model.mapLink(eventsRelation, link -> link.expand(Map.of("sorted", true)));

        return model;
    }

}
