
spring:
  web:
    error:
      include-binding-errors: always
      include-message: always
      include-stacktrace: always

logging:
  level:
    com.klabis: DEBUG
    org.springframework.security: DEBUG
    org.springframework.modulith.events: DEBUG
