spring:
  mail:
    host: ${KLABIS_SMTP_HOST}
    port: ${KLABIS_SMTP_PORT:8026}
    username: ${KLABIS_SMTP_USERNAME:klabis}
    password: ${KLABIS_SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${KLABIS_SMTP_SSL_TRUST:}

