server:
  http2:
    enabled: true
  ssl:
    key-store: classpath:https/keystore.p12
    key-store-password: secret
    #key-password: another-secret
    key-store-type: PKCS12
    key-alias: klabisSSL
  port: 8443