spring:
  mail:
    host: ${KLABIS_SMTP_HOST}
    port: ${KLABIS_SMTP_PORT:587}
    username: ${KLABIS_SMTP_USERNAME:}
    password: ${KLABIS_SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

