apiVersion: 1
datasources:
  #  - name: Loki
  #    type: loki
  #    access: proxy
  #    orgId: 1
  #    url: http://loki:3100
  #    isDefault: false
  #    basicAuth: false
  #    version: 1
  #    editable: false
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false