export const labels = {
    nav: {
        home: 'Domů',
        calendar: 'Kalendář',
        events: 'Akce',
        members: 'Členové',
        groups: 'Skupiny',
        'training-groups': 'Tréninkové skupiny',
        'family-groups': 'Rodinné skupiny',
        'category-presets': 'Šablony kategorií',
        'event-types': 'Typy akcí',
        account: 'Finance',
        'membership-fee-levels': 'Katalog úrovní',
        'fee-year-publications': 'Vypsání pro rok',
        'membership-fees': 'Členské příspěvky',
    },

    buttons: {
        submit: 'Odeslat',
        submitting: 'Odesílám...',
        importing: 'Importuji...',
        cancel: 'Zrušit',
        close: 'Zavřít',
        retry: 'Zkusit znovu',
        logout: 'Odhlásit',
        edit: 'Upravit',
        save: 'Uložit změny',
        saveChanges: 'Uložit změny',
        print: 'Tisknout',
        downloadCsv: 'Stáhnout CSV',
        accommodationList: 'Seznam pro ubytování',
        savePermissions: 'Uložit oprávnění',
        sendRequest: 'Odeslat žádost',
        setPassword: 'Nastavit heslo a aktivovat účet',
        addItem: 'Přidat',
        removeItem: 'Odebrat',
        accept: 'Přijmout',
        reject: 'Odmítnout',
        selectFromTemplates: 'Vybrat ze šablon',
    },

    templates: {
        cancelEvent: 'Zrušit akci',
        unregisterFromEvent: 'Odhlásit se z akce',
        editRegistration: 'Upravit přihlášku',
        updateEvent: 'Upravit',
        registerForEvent: 'Přihlásit se',
        publishEvent: 'Publikovat',
        createEvent: 'Přidat akci',
        importEvent: 'Importovat z ORIS',
        syncEventFromOris: 'Synchronizovat z ORISu',
        syncAllUpcomingFromOris: 'Synchronizovat všechny budoucí z ORIS',
        createCalendarItem: 'Přidat položku',
        suspendMember: 'Ukončit členství',
        resumeMember: 'Reaktivovat',
        updateMember: 'Upravit profil',
        registerMember: 'Registrovat člena',
        createGroup: 'Vytvořit skupinu',
        updateGroup: 'Upravit název',
        deleteGroup: 'Smazat skupinu',
        addGroupMember: 'Přidat člena',
        removeGroupMember: 'Odebrat',
        inviteMember: 'Pozvat člena',
        createTrainingGroup: 'Vytvořit tréninkovou skupinu',
        updateTrainingGroup: 'Upravit skupinu',
        deleteTrainingGroup: 'Smazat tréninkovou skupinu',
        addTrainingGroupMember: 'Přidat člena',
        removeTrainingGroupMember: 'Odebrat',
        createFamilyGroup: 'Vytvořit rodinnou skupinu',
        addOwner: 'Přidat správce',
        removeOwner: 'Odebrat správce',
        addGroupOwner: 'Přidat správce',
        removeGroupOwner: 'Odebrat správce',
        addTrainer: 'Přidat trenéra',
        removeTrainer: 'Odebrat trenéra',
        addFamilyGroupParent: 'Přidat rodiče',
        removeFamilyGroupParent: 'Odebrat rodiče',
        addFamilyGroupChild: 'Přidat dítě',
        removeFamilyGroupChild: 'Odebrat',
        addFamilyGroupMember: 'Přidat člena',
        deleteFamilyGroup: 'Smazat rodinnou skupinu',
        cancelInvitation: 'Zrušit pozvánku',
        createCategoryPreset: 'Přidat šablonu',
        updateCategoryPreset: 'Upravit šablonu',
        deleteCategoryPreset: 'Smazat šablonu',
        createEventType: 'Přidat typ akce',
        updateEventType: 'Upravit typ akce',
        deleteEventType: 'Smazat typ akce',
        deposit: 'Vložit',
        charge: 'Strhnout',
        reverse: 'Stornovat',
        createMembershipFeeLevel: 'Přidat úroveň',
        updateMembershipFeeLevel: 'Upravit úroveň',
        deleteMembershipFeeLevel: 'Smazat úroveň',
        publishFeeYear: 'Vypsat rok',
        updateMembershipFeeGroup: 'Upravit skupinu',
        assignMember: 'Přiřadit člena',
    },

    dialogTitles: {
        selectCategoryPreset: 'Vybrat šablonu kategorií',
        publishEvent: 'Publikování akce',
        cancelEvent: 'Zrušení akce',
        registerForEvent: 'Přihlásit se na akci',
        unregisterFromEvent: 'Odhlásit se z akce',
        editRegistration: 'Upravit přihlášku',
        suspendMember: 'Ukončení členství',
        resumeMember: 'Reaktivace člena',
        importEvent: 'Import akce z ORIS',
        syncAllUpcomingFromOris: 'Hromadná synchronizace z ORIS',
        createEvent: 'Nová akce',
        registerMember: 'Registrace nového člena',
    },

    bulkSync: {
        progress: 'Synchronizuji...',
        successCount: (n: number) => `${n} úspěšně synchronizováno`,
        failureCount: (n: number) => `${n} chyb`,
        failuresHeading: 'Chyby:',
    },

    orisImport: {
        dialogTitle: 'Importovat z ORIS',
        selectAll: 'Vybrat vše',
        selectedOf: (selected: number, total: number) => `Vybráno ${selected} z ${total} závodů`,
        showOnlySelected: 'Zobrazit jen vybrané',
        clearSelection: 'Zrušit výběr',
        shownOf: (shown: number, total: number) => `zobrazeno ${shown} z ${total}`,
        importSelected: (n: number) => `Importovat vybrané (${n})`,
        loadingMessage: 'Komunikuji s ORIS…',
        emptyHeading: 'Žádné závody k importu',
        emptyHint: 'Zkuste změnit oblast.',
        resultTitle: 'Výsledek importu',
        resultSummary: (success: number, total: number) => `Naimportováno ${success} z ${total}`,
        importFailed: 'Import se nezdařil. Zkuste to prosím znovu.',
        done: 'Hotovo',
        limitReachedHint: (limit: number) => `Můžete vybrat nejvýše ${limit} závodů.`,
    },

    fields: {
        eventCoordinatorId: 'Vedoucí',
        eventDate: 'Datum konání',
        registrationDeadline: 'Uzávěrka',
        deadlines: 'Uzávěrky přihlášek',
        cancellationReason: 'Důvod zrušení (volitelné)',
        category: 'Kategorie',
        categories: 'Kategorie',
        location: 'Místo',
        name: 'Název',
        organizer: 'Pořadatel',
        websiteUrl: 'Webová stránka',
        firstName: 'Jméno',
        lastName: 'Příjmení',
        email: 'E-mail',
        phone: 'Telefon',
        birthDate: 'Datum narození',
        dateOfBirth: 'Datum narození',
        gender: 'Pohlaví',
        nationality: 'Státní příslušnost',
        birthNumber: 'Rodné číslo',
        registrationNumber: 'Registrační číslo',
        chipNumber: 'Číslo čipu',
        bankAccountNumber: 'Číslo bankovního účtu',
        dietaryRestrictions: 'Stravovací omezení',
        drivingLicenseGroup: 'Řidičský průkaz',
        memberId: 'Člen',
        memberIds: 'Členové',
        parentIds: 'Rodiče',
        trainerId: 'Trenér',
        minAge: 'Min. věk',
        maxAge: 'Max. věk',
        memberCount: 'Počet členů',
        ageRange: 'Věkové rozmezí',
        reason: 'Důvod zrušení (volitelné)',
        color: 'Barva',
        sortOrder: 'Pořadí',
        eventTypeId: 'Typ akce',
        orisDisciplineIds: 'ORIS disciplíny',
        ranking: 'Žebříček',
        baseEntryFee: 'Startovné',
        annualFee: 'Roční poplatek',
        choiceDeadline: 'Uzávěrka voleb',
        groupStatus: 'Stav skupiny',
        ruleType: 'Typ pravidla',
        percentage: 'Procento (%)',
        fixedSurcharge: 'Fixní příplatek (Kč)',
        raceTypeId: 'Typ závodu',
        source: 'Zdroj přiřazení',
    },

    finance: {
        memberAccountPageTitle: 'Finance',
        balance: 'Zůstatek',
        transactionHistory: 'Historie transakcí',
        noTransactions: 'Žádné transakce',
        deposit: 'Vložit',
        charge: 'Strhnout',
        reverse: 'Stornovat',
        confirmReverse: 'Potvrdit storno',
        cancelReverse: 'Zrušit',
        reverseConfirmTitle: 'Stornovat transakci',
        reverseConfirmDescription: 'Storno vytvoří novou transakci opačného znamínka. Tuto akci nelze vrátit zpět.',
        date: 'Datum',
        type: 'Typ',
        amount: 'Částka',
        description: 'Popis',
        reversed: 'Stornováno',
        reversal: 'Storno',
        navigateToReversal: 'Zobrazit storno',
        navigateToOriginal: 'Zobrazit původní transakci',
        typeDeposit: 'Vklad',
        typeOther: 'Výdaj',
        filterDateFrom: 'Datum od',
        filterDateTo: 'Datum do',
        filterType: 'Typ',
        filterTypeAll: 'Vše',
        currency: 'Kč',
        openMemberAccount: 'Účet',
        transactionDialogTitle: 'Vložit / Vybrat',
        tabDeposit: 'Připsání vkladu',
        tabCharge: 'Stržení částky',
        openTransactionDialogAriaLabel: 'Provést finanční transakci',
        amountRequired: 'Částka *',
        note: 'Poznámka',
        notePlaceholder: 'Volitelná poznámka...',
        noOperationAllowed: 'Žádná operace není povolena',
        recordedBy: 'Zaznamenal',
    },

    enums: {
        eventStatus: {
            ACTIVE: 'Aktivní',
            FINISHED: 'Ukončeno',
            CANCELLED: 'Zrušeno',
            DRAFT: 'Koncept',
        },
        memberStatus: {
            active: 'Aktivní',
            inactive: 'Neaktivní',
        },
        gender: {
            MALE: 'Muž',
            FEMALE: 'Žena',
        },
        deactivationReason: {
            ODHLASKA: 'Odhlášení',
            PRESTUP: 'Přestup',
            OTHER: 'Jiný důvod',
        },
        feeGroupStatus: {
            EDITABLE: 'Editovatelná',
            FROZEN: 'Zmrazená',
        },
        feeMemberSource: {
            MEMBER_CHOICE: 'Vlastní volba',
            ADMIN_ASSIGNMENT: 'Přiřazeno adminem',
        },
    },

    validation: {
        requiredField: 'Povinné pole',
        invalidEmail: 'Neplatný email',
        mustBeNumber: 'Musí být číslo',
        invalidFormat: 'Nespravny format',
        registrationNumberRequired: 'Registrační číslo je povinné',
        emailRequired: 'Email je povinný',
        emailInvalidFormat: 'Email má neplatný formát',
        passwordRequirements: 'Heslo nesplňuje všechny požadavky',
        passwordsMismatch: 'Hesla se neshodují',
    },

    errors: {
        invalidCredentials: 'Nesprávné registrační číslo nebo heslo',
        configurationError: 'Chyba konfigurace, kontaktujte administrátora',
        loadingMenu: 'Načítání menu...',
        noMenuItems: 'Žádné položky menu',
        failedLoadMenu: 'Nepodařilo se načíst menu',
        formValidationErrors: 'Chyby validace formuláře',
        formDataLoadError: 'Nepodařilo se načíst data formuláře',
        rateLimitedRetryAfter: 'Požadavek byl omezen. Zkuste to znovu za {seconds} sekund.',
        rateLimitedRetryLater: 'Požadavek byl omezen. Zkuste to prosím později.',
        requestFailed: 'Požadavek selhal.',
        unexpectedError: 'Došlo k neočekávané chybě. Zkuste to prosím znovu.',
        tokenExpired: 'Platnost tokenu vypršela nebo byl již použit. Požádejte si o nový.',
        tokenInvalid: 'Neplatný token. Požádejte si o nový.',
        savePermissionsFailed: 'Nepodařilo se uložit oprávnění. Zkuste to prosím znovu.',
        removeLastPermissionsAdmin: 'Nelze odebrat oprávnění správce — systém musí mít alespoň jednoho uživatele se správou oprávnění.',
        memberRegistrationUnavailable: 'Registrace nového člena není k dispozici.',
        importOrisConflict: 'Tato akce již byla importována.',
        importOrisFailed: 'Import akce se nezdařil. Zkuste to prosím znovu.',
        importOrisLoadFailed: 'Nepodařilo se načíst akce z ORIS.',
        importOrisNoEvents: 'Žádné akce k importu.',
    },

    orisRegions: {
        JIHOMORAVSKA: 'Jihomoravská',
        MORAVA: 'Žebříček Morava',
        CR: 'ČR',
    } as Record<string, string>,

    familyGroupRoles: {
        parent: 'Rodič',
        child: 'Dítě',
    },

    ui: {
        hide: 'Skrýt',
        reveal: 'Zobrazit',
        currentDeadline: 'aktuální',
        deadlineOrdinal: (n: number) => `${n}. termín:`,
        deadlineOrdinalShort: (n: number) => `${n}. termín`,
        notProvided: 'neuvedeno',
        form: 'Formulář',
        showRawJson: 'Zobrazit zdrojový JSON',
        completeJson: 'Úplná JSON data položky',
        availableActions: 'Dostupné odkazy',
        availableForms: 'Dostupné formuláře',
        collectionEmpty: 'Kolekce je prázdná',
        viewFullJson: 'Zobrazit celý JSON',
        loadingFormData: 'Načítání dat formuláře...',
        loading: 'Načítání...',
        navigation: 'Navigace',
        appName: 'Klabis Club Manager',
        appVersion: 'Verze 1.0.0',
        showMemberDetails: 'Zobrazit detail člena',
        backToList: '← Zpět na seznam',
        switchToDark: 'Přepnout do tmavého režimu',
        switchToLight: 'Přepnout do světlého režimu',
        themeDark: 'Tmavý',
        themeLight: 'Světlý',
        menuLoadError: 'Chyba při načítání menu',
        noMenuAvailable: 'Žádné položky menu nejsou dostupné',
        navAdminSection: 'Administrace',
        calendarSubtitle: 'Kalendář akcí a důležitých dat',
        prevMonth: 'Předchozí měsíc',
        nextMonth: 'Následující měsíc',
        mySchedule: 'Můj rozvrh',
        emailSent: 'Email byl odeslán',
        emailSentDescription: 'Pokud je váš účet stále čekající na aktivaci, obdržíte email s odkazem pro nastavení hesla. Zkontrolujte prosím svou schránku.',
        passwordSetSuccess: 'Heslo úspěšně nastaveno',
        passwordSetSuccessDescription: 'Váš účet byl aktivován. Nyní budete přesměrováni na přihlašovací stránku.',
        permissionsDescription: 'Oprávnění určují, ke kterým funkcím aplikace má uživatel přístup. Změny se projeví okamžitě.',
        permissionsSaved: 'Oprávnění uložena',
        savedSuccessfully: 'Úspěšně uloženo',
        notAssigned: 'Není přiřazen',
    },

    tables: {
        id: 'ID',
        data: 'Údaje',
        actions: 'Akce',
        attribute: 'Atribut',
        value: 'Hodnota',
        items: 'Položky',
        details: 'Detaily',
        status: 'Status',
        date: 'Datum',
        registeredAt: 'Datum přihlášení',
        joinedAt: 'Datum vstupu',
        web: 'Web',
        registrationDeadline: 'Uzávěrka',
        coordinator: 'Vedoucí',
        identityCardNumber: 'Číslo OP',
        identityCardValidityDate: 'Platnost OP',
        dateOfBirth: 'Datum narození',
        address: 'Adresa',
        eventType: 'Typ',
    },

    sections: {
        members: 'Členové',
        membersList: 'Seznam členů',
        events: 'Akce',
        eventsList: 'Seznam akcí',
        eventInfo: 'INFORMACE O AKCI',
        registrations: 'Přihlášky',
        deadlines: 'UZÁVĚRKY PŘIHLÁŠEK',
        eventCancelled: 'AKCE BYLA ZRUŠENA',
        accommodationList: 'Seznam pro ubytování',
        personalInfo: 'OSOBNÍ ÚDAJE',
        contact: 'KONTAKT',
        address: 'ADRESA',
        supplementary: 'DOPLŇKOVÉ INFORMACE',
        documentsAndLicenses: 'DOKLADY A LICENCE',
        guardian: 'ZÁKONNÝ ZÁSTUPCE',
        deactivation: 'DEAKTIVACE',
        groups: 'Skupiny',
        groupsList: 'Moje skupiny',
        groupOwners: 'SPRÁVCI',
        groupMembers: 'ČLENOVÉ',
        pendingInvitations: 'ČEKAJÍCÍ POZVÁNKY',
        trainingGroupsList: 'Tréninkové skupiny',
        trainingGroupMembers: 'ČLENOVÉ',
        trainingGroupTrainers: 'TRENÉŘI',
        trainingGroup: 'TRÉNINKOVÁ SKUPINA',
        familyGroup: 'RODINNÁ SKUPINA',
        familyGroups: 'Rodinné skupiny',
        familyGroupsList: 'Rodinné skupiny',
        familyGroupParents: 'RODIČE',
        familyGroupChildren: 'DĚTI',
        familyGroupMembers: 'ČLENOVÉ',
        categoryPresetsList: 'Šablony kategorií',
        presetsListHeading: 'Seznam šablon',
        eventTypesList: 'Typy akcí',
        eventTypesListHeading: 'Seznam typů akcí',
        eventBasicInfo: 'ZÁKLADNÍ INFORMACE',
        eventCoordination: 'VEDENÍ AKCE',
        eventDeadlines: 'UZÁVĚRKY PŘIHLÁŠEK',
        eventCategories: 'KATEGORIE',
        membershipFeeLevelsList: 'Katalog úrovní',
        membershipFeeGroups: 'Skupiny',
        membershipFeeGroupMembers: 'ČLENOVÉ',
        feeYearPublicationsList: 'Vypsání pro rok',
        coParticipationRules: 'PRAVIDLA SPOLUÚČASTI',
    },

    dashboard: {
        welcome: 'Vítejte v Klabis',
        subtitle: 'Moderní systém pro správu členského klubu',
        activeMembers: 'Aktivních členů',
        upcomingEvents: 'Nadcházející akce',
        groups: 'Skupiny a týmy',
        systemStatus: 'Systémový status',
        online: 'Online',
        myProfile: 'Můj profil',
        myEvents: 'Moje nadcházející akce',
        openSection: 'Otevřít',
        noUpcomingEvents: 'Žádné nadcházející akce',
        showAll: 'Zobrazit všechny',
        browseClubEvents: 'Prohlédnout nadcházející akce klubu',
        eventsPanelTitle: 'Akce',
        eventsPanelSubtitle: 'Všechny nadcházející akce',
        upcomingDeadlinesTitle: 'Končící přihlášky tento týden',
        deadlinePrefix: 'Uzávěrka:',
        registerForEvent: 'Přihlásit se',
        showAllDeadlines: 'Zobrazit všechny s končící uzávěrkou',
    },

    permissions: {
        'MEMBERS:MANAGE': {label: 'Správa členů', description: 'Registrace, úprava a mazání členů'},
        'MEMBERS:PERMISSIONS': {label: 'Správa oprávnění', description: 'Přidělování a odebírání oprávnění uživatelům'},
        'EVENTS:MANAGE': {label: 'Správa akcí', description: 'Vytváření a úprava akcí'},
        'CALENDAR:MANAGE': {label: 'Správa kalendáře', description: 'Vytváření a úprava kalendářních událostí'},
        'GROUPS:TRAINING': {label: 'Správa tréninkových skupin', description: 'Umožňuje vytvářet a spravovat tréninkové skupiny a jejich členy.'},
        'EVENTS:REGISTRATIONS': {label: 'Správa přihlášek', description: 'Editace přihlášek ostatních členů na akce'},
        'FINANCE:MANAGE': {label: 'Správa financí', description: 'Vklady, strhávání a storno transakcí na účtech členů'},
    },

    links: {
        trainingGroup: 'Tréninková skupina',
        familyGroup: 'Rodina',
    },

    eventsFilter: {
        search: 'Hledat',
        searchPlaceholder: 'Hledat podle názvu nebo místa...',
        timeWindowLabel: 'Zobrazit',
        budouci: 'Budoucí',
        probehle: 'Proběhlé',
        vse: 'Vše',
        mojePřihlaskyLabel: 'Moje přihlášky',
        emptyState: 'Žádné akce neodpovídají zadaným filtrům.',
        eventTypeSelectPlaceholder: '— bez filtru —',
        eventTypeFilter: 'Typ akce',
        eventTypeAll: 'Vše',
        eventsFilterYear: 'Rok',
        noYear: '—',
        timeWindowDisabledTooltip: 'Není k dispozici pro jiný než aktuální rok',
    },

    membersFilter: {
        search: 'Hledat člena',
        searchPlaceholder: 'Hledat podle jména nebo registračního čísla',
        statusLabel: 'Stav členství',
        statusActive: 'Aktivní',
        statusInactive: 'Neaktivní',
        statusAll: 'Vše',
        emptyState: 'Žádní členové neodpovídají zadaným filtrům.',
    },

    suspensionWarning: {
        title: 'Varování: Správce skupin',
        description: 'Člen je posledním správcem následujících skupin. Před ukončením členství je nutné určit nástupce nebo skupiny rozpustit.',
        designateSuccessor: 'Určit nástupce',
        dissolveGroup: 'Rozpustit skupinu',
        trainingGroupNote: 'U tréninkové skupiny je nutné určit nástupce.',
        groupTypeTrainingGroup: 'Tréninková skupina',
        groupTypeFamilyGroup: 'Rodinná skupina',
        groupTypeFreeGroup: 'Volná skupina',
    },

    negativeBalanceWarning: {
        title: 'Záporný zůstatek',
        description: 'Pro ukončení členství musí být zůstatek nezáporný. Nejprve doplňte prostředky na účtu člena.',
        currentBalance: 'Aktuální zůstatek',
        openAccount: 'Otevřít účet',
        close: 'Zavřít',
    },

    changePassword: {
        sectionButtonLabel: 'Změnit heslo',
        dialogTitle: 'Změna hesla',
        currentPasswordLabel: 'Aktuální heslo',
        newPasswordLabel: 'Nové heslo',
        confirmPasswordLabel: 'Potvrzení nového hesla',
        submitButton: 'Změnit heslo',
        errorIncorrectCurrentPassword: 'Zadané aktuální heslo je nesprávné.',
    },

    memberFee: {
        choicePageTitle: (year: number) => `Výběr úrovně členského příspěvku pro rok ${year}`,
        sectionTitle: 'ČLENSKÝ PŘÍSPĚVEK',
        currentLevel: 'Aktuální úroveň příspěvku',
        choiceLevel: 'Výběr úrovně příspěvku',
        deadlineExpired: 'Lhůta pro výběr uplynula',
        chooseLevel: 'Zvolit úroveň',
        changeLevel: 'Změnit úroveň',
        cancelChoice: 'Zrušit volbu',
        noChoiceMade: 'Výběr ještě nebyl proveden',
        viewHistory: 'Zobrazit historii příspěvků',
        feeLevel: 'Úroveň členského příspěvku',
        annualFee: 'Roční poplatek',
        noChoiceWarning: 'Lhůta pro výběr příspěvku uplynula bez provedené volby.',
        choiceLockedInfo: 'Volba je uzamčena.',
        votingOpenChoiceExists: 'Máte zvolenu úroveň příspěvku. Volbu je možné změnit.',
        votingOpenNoChoice: 'Probíhá volba úrovně příspěvku. Zvolte si svou úroveň.',
    },

    calendarFeed: {
        sectionTitle: 'KALENDÁŘOVÝ FEED',
        intro: 'Přihlaste se k odběru svých akcí v externím kalendáři.',
        createButton: 'Vytvořit kalendářový feed',
        regenerateButton: 'Vygenerovat nový token',
        copyButton: 'Kopírovat',
        copiedButton: 'Zkopírováno',
        generatedAt: 'Vygenerováno',
        confirmRegenerateTitle: 'Vygenerovat nový token?',
        confirmRegenerateMessage: 'Předchozí URL přestane fungovat. Všechna zařízení, která ji používají, se přestanou synchronizovat, dokud nezadáte novou URL.',
        confirmRegenerateAction: 'Vygenerovat',
        fullUrlLabel: 'URL kalendářového feedu',
        fullUrlNote: 'Tuto URL uvidíte pouze nyní. Uložte ji nebo přidejte do svého kalendáře. Pokud ji ztratíte, vygenerujte nový token.',
        maskedUrlLabel: 'Subscribe URL (zamaskovaná)',
        helpTitle: 'Jak přidat do kalendáře',
        helpText: 'Přidejte tuto URL do svého kalendáře — Google Calendar, Apple Calendar nebo Outlook. Kalendář se automaticky aktualizuje, jak budete přihlašovat nebo odhlašovat akce, nebo když vám organizátor přidá či odebere roli koordinátora.',
        helpMyScheduleNote: 'Feed obsahuje stejné akce jako filtr „Můj rozvrh" v aplikaci — akce, kde máte aktivní přihlášku nebo jste koordinátorem.',
        helpGoogle: 'Google Calendar: Jiné kalendáře → Přidat URL',
        helpApple: 'Apple Calendar: Soubor → Nový odběr kalendáře',
        helpOutlook: 'Outlook: Přidat kalendář → Odebírat z webu',
    },
} as const;

export type Labels = typeof labels;
export type LabelCategory = keyof Labels;

export function t<C extends LabelCategory>(category: C, key: keyof Labels[C]): string {
    return labels[category][key] as string;
}

export function getFieldLabel(fieldName: string, formOverrides?: Record<string, string>): string {
    if (formOverrides && fieldName in formOverrides) {
        return formOverrides[fieldName];
    }
    const fieldLabels = labels.fields as Record<string, string>;
    return fieldLabels[fieldName] ?? fieldName;
}

export function getTemplateLabel(templateName: string): string | undefined {
    const templateLabels = labels.templates as Record<string, string>;
    return templateLabels[templateName];
}

export function getDialogTitleLabel(templateName: string): string | undefined {
    const dialogTitleLabels = labels.dialogTitles as Record<string, string>;
    return dialogTitleLabels[templateName];
}

export function getNavLabel(rel: string): string {
    const navLabels = labels.nav as Record<string, string>;
    return navLabels[rel] ?? rel;
}

export function getEnumLabel(enumType: string, value: string): string {
    const enumGroups = labels.enums as Record<string, Record<string, string>>;
    return enumGroups[enumType]?.[value] ?? value;
}
