name: Backend Tests

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend_publish.yml'
  workflow_dispatch: # Manual trigger

jobs:
  test:
    name: Gradle Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Run tests with Gradle
        working-directory: backend
        run: ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: backend/build/reports/tests/
